### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by hdddhdd** [happinesslz/LION#10]
Hello,
I thoroughly enjoyed reading your paper "LION: Linear Group RNN for 3D Object Detection in Point Clouds."

I am also interested in conducting research using autonomous driving datasets, and I have a question regarding data visualization. Could you share how you approached the visualization in your work and point me to the code where I can find it? 

Thank you.

**Comment by happinesslz** [comment]
@hdddhdd Thanks for your attention! We will release this code of this visualization. @deepinact

**Comment by hdddhdd** [comment]
Thank you for your response! 

I'm not too familiar with this, so I was wondering what viewers researchers commonly use for 3D autonomous driving datasets?

**Comment by happinesslz** [comment]
@hdddhdd Hi, open3d or mayavi may be a good choice. You could refer to the open-source code of OpenPCDet (https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md) and have a try.

**Comment by hdddhdd** [comment]
Thank you for the detailed response😊!! I will try those things.

**Comment by deepinact** [comment]
I've been quite busy lately, but I'll clean up the code for the visualization of the BEV perspective and feature map and release it as soon as possible afterward. As for the visualization of 3D perspective, we achieved that using Open3D.
