### ISSUE TITLE
求卡支援

### ISSUE THREAD

**Issue by rubbish001** [happinesslz/LION#11]
我用的是180 x 180的配置test刷的NDS72.9%，mAP69.1%，我看你的配置是256 x 256的BEV，同等配置刷一波，看看你的厉害，还是我的厉害

**Comment by AlmoonYsl** [comment]
> 我用的是180 x 180的配置test刷的NDS72.9%，mAP69.1%，我看你的配置是256 x 256的BEV，同等配置刷一波，看看你的厉害，还是我的厉害

您好，LION的detection head中的BEV大小也是180 x 180的

**Comment by rubbish001** [comment]
![image](https://github.com/user-attachments/assets/373305e0-d4e3-446c-8aed-fe2fa7d80ed2)
你这个grid_size是0.4啊，对应的应该是256*256,180对应的是0.6

**Comment by AlmoonYsl** [comment]
> ![image](https://private-user-images.githubusercontent.com/4549184/364691634-373305e0-d4e3-446c-8aed-fe2fa7d80ed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjU1NDUsIm5iZiI6MTcyNTUyNTI0NSwicGF0aCI6Ii80NTQ5MTg0LzM2NDY5MTYzNC0zNzMzMDVlMC1kNGUzLTQ0NmMtOGFlZC1mZTJmYTdkODBlZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDgzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgwMzJmYTdhZDkzYjMxMzY3NmVjNTQyYjA2YzEwZjU4NzgwNjNmYzA0YWM5MzRjZjBmYzBhNmVjY2RlNjIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lv9txqbV7ZmSFZAUEh0IWBHQRYnaegnJdr9AhY-jKMY) 你这个grid_size是0.32啊，比0.4还小，我看错了，180对应的是0.6

抱歉，nuScenes上的grid_size是[0.3m, 0.3m, 0.25]，论文中有笔误。此外，在BEV Backbone中我们降采样了2倍，因此最后BEV的大小是180

**Comment by rubbish001** [comment]
哦哦，你这个思路也可以，因为我最近跑了一下0.4的配置，发现NDS在val数据集中比我原来的上涨了1.6，你这个配置我还没有试过

**Comment by AlmoonYsl** [comment]
> 哦哦，你这个思路也可以，因为我最近跑了一下0.4的配置，发现NDS在val数据集中比我原来的上涨了1.6，你这个配置我还没有试过

您可以试试，期待您的结果

**Comment by rubbish001** [comment]
现在主要是在搞Co-stream ，就是没有卡跑，坑的一b
