### ISSUE TITLE
Can LION use sparsehead to predict object?

### ISSUE THREAD

**Issue by qifeng22** [happinesslz/LION#12]
Thanks for your excellent work. do you try to use the sparse detection head to predict object? Like the [https://arxiv.org/abs/2403.05817](SAFDNet), will this method can save the inference time?
@happinesslz

**Comment by qifeng22** [comment]
SAFDNet

**Comment by happinesslz** [comment]
@qifeng22 Yes, it will. For sparse detection head (similar with SAFDNet and VoxelNext), you could refer to [lion_models/lion_mamba_1f_1x_argo_128dim_sparse_v2.yaml](https://github.com/happinesslz/LION/blob/main/tools/cfgs/lion_models/lion_mamba_1f_1x_argo_128dim_sparse_v2.yaml), which could save much more inference time compared with dense detection head.
