### ISSUE TITLE
Numpy & av2 conflict 

### ISSUE THREAD

**Issue by GP-Bone** [happinesslz/LION#15]
Thanks for your work.
   I am facing a version conflict issue between NumPy and OpenCV. av2 requires numpy that is newer than 1.20 to use numpy. And we need numpy ==1.19.5.
   Could you kindly share some suggestions? Thank you once again for your outstanding work.

**Comment by AlmoonYsl** [comment]
> Thanks for your work. I am facing a version conflict issue between NumPy and OpenCV. av2 requires numpy that is newer than 1.20 to use numpy. And we need numpy ==1.19.5. Could you kindly share some suggestions? Thank you once again for your outstanding work.

Hi, what is the version of av2 you installed?

**Comment by GP-Bone** [comment]
> > Thanks for your work. I am facing a version conflict issue between NumPy and OpenCV. av2 requires numpy that is newer than 1.20 to use numpy. And we need numpy ==1.19.5. Could you kindly share some suggestions? Thank you once again for your outstanding work.
> 
> Hi, what is the version of av2 you installed?

I use av2==0.2.0 with OpenPCDet's requirements. Then the numpy is forced to upgrade.

**Comment by happinesslz** [comment]
@GP-Bone Hi, If you use argoverse v2(not waymo), it is ok for numpy==1.23.5.  However, for waymo or other datasets, maybe you need switch numpy to 1.19.5.

**Comment by GP-Bone** [comment]
> @GP-Bone Hi, If you use argoverse v2(not waymo), it is ok for numpy==1.23.5. However, for waymo or other datasets, maybe you need switch numpy to 1.19.5.

Using different conda environments for various datasets is indeed a wise approach. I have overcomplicated the issue in my mind. Thanks very much for your response!!!
