### ISSUE TITLE
Will the batch size significantly affect the results on the Waymo validation dataset?

### ISSUE THREAD

**Issue by qifeng22** [happinesslz/LION#16]
![image](https://github.com/user-attachments/assets/644a00b5-1603-4101-a242-348bdcd58349)
Here is the result, the cfg file is lion_mamba_waymo_8x_1f_1x_one_stride_128dim.yaml

**Comment by qifeng22** [comment]
I train the model , batchsize = 8 ,epoch = 24

**Comment by qifeng22** [comment]
@happinesslz

**Comment by happinesslz** [comment]
@qifeng22  Maybe，please keep the same batch_size with ours. BTW, this config only uses 20% dataset for 24 epoch. The reported performance is 100% with 24 epochs. As shown in the following figure, you need to revise 5-->1 to achieve 100%dataset for training.
<img width="535" alt="image" src="https://github.com/user-attachments/assets/e1faadb7-ca89-429a-a83e-08f911ef35a9">
