### ISSUE TITLE
Is there code for inference without label?

### ISSUE THREAD

**Issue by rlgnswk** [happinesslz/LION#18]
Hi, I really appreciated  your great work.

What I ask you is that there is code for inference without label.
I want to inference some raw data which mean unknown point cloud.

Could you shared that?

Thanks.

**Comment by AlmoonYsl** [comment]
Hi, @rlgnswk 
The labels output by LION are defined by the used training dataset, but you may be able to try some checkpoints in the repo to infer your raw data.
