### ISSUE TITLE
about requirements

### ISSUE THREAD

**Issue by ppap4** [happinesslz/LION#19]
ERROR: Cannot install -r requirements.txt (line 29), -r requirements.txt (line 39), tensorflow==2.5.0 and typing_extensions==4.10.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested typing_extensions==4.10.0
    huggingface-hub 0.21.4 depends on typing-extensions>=3.7.4.3
    iopath 0.1.10 depends on typing_extensions
    tensorflow 2.5.0 depends on typing-extensions~=3.7.4

**Comment by AlmoonYsl** [comment]
@ppap4 
Hi,
Can you ignore this error and run the code successfully? The dependencies may contain some conflicts.
