### ISSUE TITLE
Is it supported multi-frame?

### ISSUE THREAD

**Issue by pycoco** [happinesslz/LION#21]

**Comment by AlmoonYsl** [comment]
@pycoco Hi,
You can concatenate multi frame point clouds for multi-frame training.

**Comment by pycoco** [comment]
> @pycoco Hi, You can concatenate multi frame point clouds for multi-frame training.

**Comment by pycoco** [comment]
> @pycoco Hi, You can concatenate multi frame point clouds for multi-frame training.

Thanks for your reply. Has Lion ever experimented with multiple frames on waymo? How is the performance?

**Comment by AlmoonYsl** [comment]
@pycoco Hi,
LION with 3 frames can achieve 77.4 mAPH/L2 on the Waymo test set.

**Comment by pycoco** [comment]
> @pycoco Hi, LION with 3 frames can achieve 77.4 mAPH/L2 on the Waymo test set.

Thanks, and another curious question is why spatial_shape does not have +[1,0,0]. I found that other sparse models added [1,0,0].

**Comment by AlmoonYsl** [comment]
@pycoco Hi,
```+[1,0,0]``` is to ensure that the downsampled voxel shapes are integers. However, LION achieves this by adjusting the input point cloud range.
