### ISSUE TITLE
Will CBGS enhance the performance of LION?

### ISSUE THREAD

**Issue by PanGao-1** [happinesslz/LION#22]
Will CBGS enhance the performance of LION?
 If I use CBGS to train LION, would you recommend training for 20 epochs or 36 epochs?

**Comment by happinesslz** [comment]
@PanGao-1 Training 20 epochs is enough. The corresponding performance has only a little improvement over the performance of training 36 epochs without CBGS.

**Comment by PanGao-1** [comment]
@happinesslz  Thank you for your response. I tried training LION with CBGS for 48 epochs, but it resulted in an even lower NDS. It seems that the LION model without CBGS has already achieved a good balance across the 10 categories. 

I am now preparing to use LION as a robust LiDAR branch for multimodal object detection. I hope to achieve better results. 
God bless you !!
