### ISSUE TITLE
LIONLayer中的分组和特征学习是否存在问题

### ISSUE THREAD

**Issue by weiyuuuuyiew** [happinesslz/LION#23]
你好，在代码LIONLayer中，先对体素特征按照窗口进行了分组，然后使用RNN算子进行变换。但是该特征包含了一个batch里面的全部特征，而不是单个数据特征，这样直接对其使用mamba之类的算子进行特征学习，单个数据会学习到其它数据的特征？会存在问题吗
![image](https://github.com/user-attachments/assets/52c4cfa7-6675-4b70-b76f-87ef7d328d10)

**Comment by weiyuuuuyiew** [comment]
@happinesslz

**Comment by AlmoonYsl** [comment]
@weiyuuuuyiew 
您好，该特征形状为（B，L，C），不同batch和一个batch中的分组数量的总和为B，因此不会有batch间的特征交互。

**Comment by weiyuuuuyiew** [comment]
> @weiyuuuuyiew 您好，该特征形状为（B，L，C），不同batch和一个batch中的分组数量的总和为B，因此不会有batch间的特征交互。

谢谢您，我理解错了。block应该学习的是每个分组内的数据
