### ISSUE TITLE
训练集loss上升

### ISSUE THREAD

**Issue by weiyuuuuyiew** [happinesslz/LION#24]
您好，我在使用lion_mamba_nusc_8x_1f_1x_one_stride_128dim_ep48.yaml进行训练的时候，发现训练集的loss在第5个epoch降到2.53左右，
![image](https://github.com/user-attachments/assets/c5b5321c-e715-4c29-ae9d-f6cbe1882e89)
然后一直至第15个epoch持续上升至2.87左右
![image](https://github.com/user-attachments/assets/623c7e68-6a0b-4969-935d-0e1eacc99fca)
同时我发现loss上升的时候学习率也在升高，这和学习率有关吗？
因为设备限制导致训练周期过长，特来问询，如有打扰还望海涵

**Comment by weiyuuuuyiew** [comment]
@happinesslz

**Comment by AlmoonYsl** [comment]
@weiyuuuuyiew 
您好，您可以提供下您的训练参数是什么吗？（GPU、batch size、学习率），如果和仓库中的设置对齐的话最终复现性能是没问题的。

**Comment by weiyuuuuyiew** [comment]
> @weiyuuuuyiew 您好，您可以提供下您的训练参数是什么吗？（GPU、batch size、学习率），如果和仓库中的设置对齐的话最终复现性能是没问题的。

您好，谢谢您的回复！我的学习率是按照配置文件进行设置，没有进行改动。我使用的是2张4080，因为显存限制，每一张卡的batch_size = 1。因为我按照您代码里面对mamba的使用方式无法导入Block，
![f5f02ad94df0404c0d339e131c7b7afd](https://github.com/user-attachments/assets/b6e4f998-0385-4c64-a5bc-3488c01c1a55)
并且我对比了mamba源码中的Block模块，和您所使用的mamba模块参数并不一致，因此我对您代码中的Mamba模块进行了改动，使用了create_block函数创建mamba块，但我认为可能不是这里的原因。其它部分未作变动，和您的工作保持一致。

**Comment by AlmoonYsl** [comment]
@weiyuuuuyiew 
您好，如果是2张卡，每张卡1 batch的话，学习率需要调整。LION默认是使用16 batch训练的，这点对于模型影响较大。

**Comment by weiyuuuuyiew** [comment]
> @weiyuuuuyiew 您好，如果是2张卡，每张卡1 batch的话，学习率需要调整。LION默认是使用16 batch训练的，这点对于模型影响较大。

您好，我也认为是我设备的问题，再次感谢！
