### ISSUE TITLE
NuScenes Performace

### ISSUE THREAD

**Issue by ihaohe** [happinesslz/LION#3]
Thanks for sharing your great work!. I reproduced the model in nuscenes using  LION-Mamba cfgs but the final performance is little lower than yours. Is it reasonable? 

8 * A100,  using LION-Mamba cfgs without any modifications

![image](https://github.com/user-attachments/assets/abd57d53-983c-4888-908f-d52f44e6f632)

**Comment by AlmoonYsl** [comment]
> Thanks for sharing your great work!. I reproduced the model in nuscenes using LION-Mamba cfgs but the final performance is little lower than yours. Is it reasonable?
> 
> 8 * A100, using LION-Mamba cfgs without any modifications
> 
> ![image](https://private-user-images.githubusercontent.com/41662686/353278971-abd57d53-983c-4888-908f-d52f44e6f632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDM2NTEsIm5iZiI6MTcyMjMwMzM1MSwicGF0aCI6Ii80MTY2MjY4Ni8zNTMyNzg5NzEtYWJkNTdkNTMtOTgzYy00ODg4LTkwOGYtZDUyZjQ0ZTZmNjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAxMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjFkMGI1OWE5ZjQ2OGMwNmFlMGE3ZGVjZDkzNDdkNzY5YTI5ZWFmYTNmNzM3ZTFmMjkxOGQxOTY1MjgyMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ToYzYVcIZKUtV4LY6cgay1Sj0I8JXPgBRrsYj1QRqs)

It is normal for nuScenes and the performance fluctuation is not very large. You can train LION-Mamba with 48 epochs for better and more stable results.

**Comment by happinesslz** [comment]
@ihaohe Thanks for your attention!   I think your reproduced results are acceptable. Our performance is mAP: 68.0 and NDS:72.1.   Therefore, the performance gap is only 0.3 mAP and 0.1 NDS. I have tried to train 48 epochs and obtain a more stable and better performance with mAP of 68.2 and NDS of 72.3. The corresponding performance is as follows:
![image](https://github.com/user-attachments/assets/769d4d15-9580-423d-a5f6-bea4472627c3)

**Comment by ihaohe** [comment]
Got it. Thank you
