### ISSUE TITLE
Question about Waymo GT file

### ISSUE THREAD

**Issue by YoushaaMurhij** [happinesslz/LION#5]
I ran evaluation step on waymo dataset and I noticed that I am missing gt.bin file.
Could you please tell me how did you get it? 
```bash
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 221, in main
    repeat_eval_ckpt(
  File "/home/user/lion/tools/test.py", line 124, in repeat_eval_ckpt
    tb_dict = eval_utils.eval_one_epoch(
  File "/home/user/lion/tools/eval_utils/eval_utils.py", line 125, in eval_one_epoch
    result_str, result_dict = dataset.evaluation(
  File "/home/user/lion/tools/../pcdet/datasets/waymo/waymo_dataset.py", line 472, in evaluation
    ap_result_str, ap_dict = waymo_fast_eval(eval_det_annos, eval_gt_annos)
  File "/home/user/lion/tools/../pcdet/datasets/waymo/waymo_dataset.py", line 453, in waymo_fast_eval
    ap_dict = eval.waymo_evaluation(
  File "/home/user/lion/tools/../pcdet/datasets/waymo/waymo_fast_eval.py", line 211, in waymo_evaluation
    ret_bytes = subprocess.check_output(command, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '../compute_detection_metrics_main ../fast_output/tmp/tmp.bin ../fast_output/gt.bin' returned non-zero exit status 127.

```
Thanks!

**Comment by AlmoonYsl** [comment]
We develop a fast waymo evaluation tool for OpenPCDet for faster evaluation, whose code is still in the organization. You can change the evaluation metric from fast_waymo to waymo in the config. Besides, we have updated it in configs of the repo.

**Comment by YoushaaMurhij** [comment]
Thanks for your response! After changing the metric to waymo, I got the evaluation metrics.
I noticed that the metrics and lower than the ones reported in your work. I am using this config:
`lion_mamba_waymo_8x_1f_1x_one_stride_128dim'.

Here are my metrics: 
```bash
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7660 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7616 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APL: 0.7660 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6813 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6773 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APL: 0.6813 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.8426 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.7913 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APL: 0.8426 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.7694 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.7202 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APL: 0.7694 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APL: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APL: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7671 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.7572 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APL: 0.7671 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.7385 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.7289 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APL: 0.7385 
```
Am I missing anything while training the model?
I did not change the config file and used one  48GB GPU.

Thanks!

**Comment by AlmoonYsl** [comment]
Hi, you trained LION with 20% training data. You can modify the ```SAMPLED_INTERVAL: {'train': 5, 'test': 1}``` to ```SAMPLED_INTERVAL: {'train': 1, 'test': 1}``` to use 100% training data for 74.0 mAPH/L2 result.

**Comment by YoushaaMurhij** [comment]
Thanks for your help. I replaced training sampling to include the whole dataset. But it seems that it need long time to train. Could you please tell, when we can expect the pretrained weights on Waymo?
Thanks

**Comment by AlmoonYsl** [comment]
> Thanks for your help. I replaced training sampling to include the whole dataset. But it seems that it need long time to train. Could you please tell, when we can expect the pretrained weights on Waymo? Thanks

Sorry, we could not provide the pretrained weights on Waymo due to the Waymo license. Please refer to the ``Additional Restrictions`` in [Waymo Dataset License Agreement](https://waymo.com/open/terms/).

**Comment by YoushaaMurhij** [comment]
I can send you my agreement [License Agreement](https://waymo.com/open/terms/) by mail if this could help!
For other datasets, is there a plan to publish them?

**Comment by happinesslz** [comment]
@YoushaaMurhij  Thanks for your attention! We will release all pretrained weights~(very sorry for not including waymo pretrained weights due to the strict Waymo License) by August 30, 2024.
