### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by AlanLiangC** [happinesslz/LION#8]
Hi, thanks for  your exelent work! Do you have any plan to provide the pre-trained weights for LION?

**Comment by happinesslz** [comment]
@AlanLiangC Thanks for your attention! We plan to provide all pre-trained weights by the end of September 2024.

**Comment by adricarda** [comment]
Hi, any updates? I am particularly interested in the pre-trained weights on the Argoverse2 dataset. Thank you.

**Comment by happinesslz** [comment]
@adricarda Hi, we will release the pre-trained weights within one week!

**Comment by adricarda** [comment]
Amazing! Thank you for your effort.

**Comment by happinesslz** [comment]
@adricarda Hi, we have released some important checkpoints in both Argoverse2 and nuScenes datasets.

**Comment by happinesslz** [comment]
@AlanLiangC Hi, we have released some important checkpoints in both Argoverse2 and nuScenes datasets.

**Comment by adricarda** [comment]
Fantastic, I really appreciate this. Thank you again.
