### ISSUE TITLE
How to solve?

### ISSUE THREAD

**Issue by 90Savage** [happinesslz/LION#9]
![Uploading 1725087288322.jpg…]()

**Comment by 90Savage** [comment]
![1725087288322](https://github.com/user-attachments/assets/ed21075a-5a08-4e75-b552-455c3d751383)

**Comment by happinesslz** [comment]
@90Savage Please keep the same version of 'typing-extensions' with our requirements.txt. Other conflicts could be ignored for running our LION.

**Comment by ChunhengH** [comment]
> @90Savage Please keep the same version of 'typing-extensions' with our requirements.txt. Other conflicts could be ignored for running our LION.

This does happen when running requirement.txt directly. I noticed that the installed version of typing-extension doesn't match the specified one either, and I'm not quite sure why that is. But after I manually installed the conflicting packages separately, the problem seemed to be solved.

**Comment by happinesslz** [comment]
@ChunhengH Yes, you need  manually install the conflicting packages.
